import { Metadata } from "next";
import Link from "next/link";

// export const metadata: Metadata = {
//   title: "안녕하세요 About Page 입니다.",
//   description: "Generated by create next app",
// };

type Props = {
  params: {
    id: string;
  };
};

export const generateMetadata = ({ params }: Props) => {
  return {
    title: "안녕하세요 About Page 입니다.",
    description: "Generated by create next app",
  };
};

function About() {
  return (
    <div>
      About 페이지입니다
      <Link href={"/about2"}>about2로 가</Link>
    </div>
  );
}

export default About;
