import Link from "next/link";

type Props = {
  params: {
    id: string; // id를 사용하는 경우에만 포함
  };
};

// metadata 생성 함수
export const generateMetadata = () => {
  return {
    title: "안녕하세요 About Page 입니다.",
    description: "Generated by create next app",
  };
};

// About 컴포넌트
function About({ params }: Props) {
  // params가 필요한 경우 사용
  return (
    <div>
      About 페이지입니다. ID: {params.id} {/* params.id를 사용 */}
      <Link href={"/about2"}>about2로 가</Link>
    </div>
  );
}

// default export
export default About;
